language: erlang

otp_release:
  - R16B

env:
  - ELIXIR_VERSION=0.11.0

before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
  - unzip -qq Precompiled.zip -d elixir

before_script:
  - export PATH=$PWD/elixir/bin:$PATH

script: mix test --trace
